#!/usr/bin/env python3
# -*- coding: utf-8 -*-


"""Convenience wrapper for running directly from source tree."""


from Jackin4Beats.Jackin4Beats import trim_audiosilence


if __name__ == '__main__':
    trim_audiosilence()
